import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Digital Library Hub",
  description: "Generated by digital library hub",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <<< Bọc children bằng AuthProvider >>> */}
        <AuthProvider>{children}</AuthProvider>
        {/* <<< Kết thúc AuthProvider >>> */}
      </body>
    </html>
  );
}
